---
- name: Log count
  hosts: all
  tasks:
    - name: file read
      with_file: "/text/test.txt"
      register: content
    - name: log count
      log_count:
        num: 1
      register: result
      debug:
        msg: "{{ result }}"