---
- hosts: all
  tasks:
    - name: file read
      debug: var=item
      register: content
      with_file:
        - /text/test.txt
    - name: log count
      log_count:
        num: 1
      register: result
      debug: var=item